jobs:
  python-ci-pylint:
    name: Python CI - Pylint
    uses: ./.github/workflows/python-ci-pylint.yaml
    with:
      python-version: ${{ inputs.python-version }}
      active: ${{ inputs.python-pylint-active }}

  python-ci-pytest:
    name: Python CI - Pytest
    uses: ./.github/workflows/python-ci-pytest.yaml
    with:
      python-version: ${{ inputs.python-version }}
      active: ${{ inputs.python-pytest-active }}

  common-ci-sonarqube:
    name: Python CI - SonarQube
    uses: ./.github/workflows/common-ci-sonarqube.yaml
    with:
      active: ${{ inputs.common-sonarqube-active }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  common-ci-dtrack:
    name: Python CI - Dependency Track
    uses: ./.github/workflows/common-ci-dtrack.yaml
    with:
      active: ${{ inputs.common-dtrack-active }}

  common-gitleaks:
    name: Python CI - Gitleaks
    uses: ./.github/workflows/common-ci-gitleaks.yaml
    with:
      active: true
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  common-ci-bandit:
    name: Python CI - Bandit
    uses: ./.github/workflows/common-ci-bandit.yaml
    with:
      active: true
